package com.example.bank.controller;

import com.example.bank.dto.AuthDto;
import com.example.bank.entity.User;
import com.example.bank.service.AuthService;
import com.example.bank.service.OtpService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.LockedException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.context.HttpSessionSecurityContextRepository;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.Map;

@RestController
@Slf4j
public class AuthController {

    private final AuthService authService;
    private final OtpService otpService;
    private final AuthenticationManager authenticationManager;
    private final String activeProfile;

    public AuthController(AuthService authService, OtpService otpService, AuthenticationManager authenticationManager,
                          @Value("${spring.profiles.active:prod}") String activeProfile) {
        this.authService = authService;
        this.otpService = otpService;
        this.authenticationManager = authenticationManager;
        this.activeProfile = activeProfile;
    }

    @PostMapping("/register")
    public ResponseEntity<?> register(@Valid @RequestBody AuthDto.RegisterRequest request) {
        try {
            User user = authService.register(request);
            log.info("User registered successfully with Nexa: {}", request.getUsername());
            return ResponseEntity.ok(Map.of(
                    "message", "Registration successful with Nexa",
                    "username", user.getUsername(),
                    "userId", user.getId()
            ));
        } catch (RuntimeException e) {
            log.error("Registration failed for username {}: {}", request.getUsername(), e.getMessage());
            return ResponseEntity.status(HttpStatus.CONFLICT)
                    .body(Map.of("code", "ERROR", "message", e.getMessage()));
        }
    }

    @PostMapping("/login")
    public ResponseEntity<?> login(@Valid @RequestBody AuthDto.LoginRequest request, HttpServletRequest httpRequest) {
        try {
            log.info("Login attempt for username: {} with Nexa", request.getUsername());

            Authentication pendingAuth = authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword())
            );

            HttpSession session = httpRequest.getSession(true);
            session.setAttribute("pendingAuth", pendingAuth);
            session.setAttribute("pendingAuthTime", LocalDateTime.now());

            User user = (User) pendingAuth.getPrincipal();
            authService.resetFailedLoginCount(user);
            otpService.generateOtp(user, "LOGIN");

            log.info("Login credentials valid for user: {}, OTP generated by Nexa", request.getUsername());

            return ResponseEntity.ok(Map.of(
                    "needMfa", true,
                    "message", "OTP generated by Nexa" +
                            ("dev".equals(activeProfile) ? ". Check the OTP in the app or server logs." : ". Contact Nexa support to receive your OTP.")
            ));
        } catch (BadCredentialsException e) {
            authService.incrementFailedLoginCount(request.getUsername());
            log.warn("Invalid credentials for user: {}", request.getUsername());
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(
                    Map.of("code", "INVALID_CREDENTIALS", "message", "Invalid credentials")
            );
        } catch (LockedException e) {
            log.warn("Account locked for user: {}", request.getUsername());
            return ResponseEntity.status(HttpStatus.LOCKED).body(
                    Map.of("code", "ACCOUNT_LOCKED", "message", "Account locked. Contact Nexa support.")
            );
        } catch (Exception e) {
            log.error("Login error for user {}: {}", request.getUsername(), e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(
                    Map.of("code", "ERROR", "message", "Login failed with Nexa: " + e.getMessage()));
        }
    }

    @PostMapping("/auth/verify-otp")
    public ResponseEntity<?> verifyOtp(@Valid @RequestBody AuthDto.OtpVerificationRequest request,
                                       HttpServletRequest httpRequest) {
        log.info("OTP verification attempt for purpose: {} from IP: {}",
                request.getPurpose(), httpRequest.getRemoteAddr());

        HttpSession session = httpRequest.getSession(false);
        if (session == null) {
            log.warn("No session found for OTP verification from IP: {}", httpRequest.getRemoteAddr());
            return ResponseEntity.badRequest().body(
                    Map.of("code", "NO_SESSION", "message", "No session found")
            );
        }

        Authentication pendingAuth = (Authentication) session.getAttribute("pendingAuth");
        LocalDateTime pendingAuthTime = (LocalDateTime) session.getAttribute("pendingAuthTime");

        if (pendingAuth == null || pendingAuthTime == null) {
            log.warn("No pending authentication found in session for IP: {}", httpRequest.getRemoteAddr());
            return ResponseEntity.badRequest().body(
                    Map.of("code", "NO_PENDING_AUTH", "message", "No pending authentication")
            );
        }

        if (pendingAuthTime.isBefore(LocalDateTime.now().minusMinutes(5))) {
            log.warn("Pending authentication expired for IP: {}", httpRequest.getRemoteAddr());
            session.removeAttribute("pendingAuth");
            session.removeAttribute("pendingAuthTime");
            return ResponseEntity.badRequest().body(
                    Map.of("code", "AUTH_EXPIRED", "message", "Authentication session expired")
            );
        }

        User user = (User) pendingAuth.getPrincipal();

        if (otpService.verifyOtp(user, request.getCode(), request.getPurpose())) {
            SecurityContextHolder.getContext().setAuthentication(pendingAuth);
            SecurityContext securityContext = SecurityContextHolder.getContext();
            session.setAttribute(HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY, securityContext);
            session.removeAttribute("pendingAuth");
            session.removeAttribute("pendingAuthTime");

            log.info("OTP verification successful for user: {} with Nexa from IP: {}",
                    user.getUsername(), httpRequest.getRemoteAddr());
            return ResponseEntity.ok(Map.of(
                    "message", "Verified with Nexa",
                    "authenticated", true
            ));
        } else {
            log.warn("Invalid OTP provided for user: {} from IP: {}",
                    user.getUsername(), httpRequest.getRemoteAddr());
            return ResponseEntity.badRequest().body(
                    Map.of("code", "INVALID_OTP", "message", "Invalid OTP")
            );
        }
    }

    @PostMapping("/auth/request-password-reset")
    public ResponseEntity<?> requestPasswordReset(@Valid @RequestBody AuthDto.PasswordResetRequest body,
                                                  HttpServletRequest httpRequest) {
        try {
            User user = authService.findUserByEmail(body.getEmail());
            otpService.generateOtp(user, "PASSWORD_RESET");
            log.info("Password reset OTP generated by Nexa for email: {} from IP: {}",
                    body.getEmail(), httpRequest.getRemoteAddr());
            return ResponseEntity.ok(Map.of(
                    "message", "Password reset OTP generated by Nexa" +
                            ("dev".equals(activeProfile) ? ". Check the OTP in the app or server logs." : ". Contact Nexa support to receive your OTP.")
            ));
        } catch (RuntimeException e) {
            log.error("Password reset request failed from IP {}: {}",
                    httpRequest.getRemoteAddr(), e.getMessage());
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(Map.of("code", "ERROR", "message", e.getMessage()));
        }
    }

    @PostMapping("/auth/confirm-password-reset")
    public ResponseEntity<?> confirmPasswordReset(@Valid @RequestBody AuthDto.PasswordResetConfirmRequest body,
                                                  HttpServletRequest httpRequest) {
        try {
            authService.confirmPasswordReset(body.getEmail(), body.getCode(), body.getNewPassword());
            log.info("Password reset completed for email: {} with Nexa from IP: {}",
                    body.getEmail(), httpRequest.getRemoteAddr());
            return ResponseEntity.ok(Map.of("message", "Password reset successful with Nexa"));
        } catch (RuntimeException e) {
            log.error("Password reset confirmation failed from IP {}: {}",
                    httpRequest.getRemoteAddr(), e.getMessage());
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(Map.of("code", "ERROR", "message", e.getMessage()));
        }
    }

    @PostMapping("/auth/reset-password")
    public ResponseEntity<?> resetPassword(@Valid @RequestBody AuthDto.PasswordResetConfirmRequest body,
                                           HttpServletRequest httpRequest) {
        log.info("Password reset endpoint called from IP: {} (redirecting to confirm-password-reset)",
                httpRequest.getRemoteAddr());
        return confirmPasswordReset(body, httpRequest);
    }

    @GetMapping("/auth/get-otp")
    public ResponseEntity<?> getLatestOtp(@RequestParam String purpose,
                                          @RequestParam(required = false) String username,
                                          Authentication authentication,
                                          HttpServletRequest httpRequest) {
        if (!"dev".equals(activeProfile)) {
            log.warn("Attempt to access OTP retrieval in non-dev profile from IP: {}", httpRequest.getRemoteAddr());
            return ResponseEntity.status(HttpStatus.FORBIDDEN)
                    .body(Map.of("code", "FORBIDDEN", "message", "OTP retrieval is only available in development mode"));
        }

        try {
            User user = null;

            // If user is authenticated, get user from authentication
            if (authentication != null && authentication.isAuthenticated() &&
                    !(authentication instanceof AnonymousAuthenticationToken)) {
                user = (User) authentication.getPrincipal();
            }
            // If not authenticated but username provided, find user by username
            else if (username != null && !username.trim().isEmpty()) {
                user = authService.findUserByUsername(username);
            }
            // For LOGIN purpose, check session for pending authentication
            else if ("LOGIN".equalsIgnoreCase(purpose)) {
                HttpSession session = httpRequest.getSession(false);
                if (session != null) {
                    Authentication pendingAuth = (Authentication) session.getAttribute("pendingAuth");
                    if (pendingAuth != null) {
                        user = (User) pendingAuth.getPrincipal();
                    }
                }
            }

            if (user == null) {
                log.warn("No user found for OTP retrieval with purpose: {} from IP: {}", purpose, httpRequest.getRemoteAddr());
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(Map.of("code", "USER_NOT_FOUND",
                                "message", "User not found. Please provide username parameter or authenticate first."));
            }

            String otp = otpService.getLatestOtp(user, purpose);
            if (otp == null) {
                log.warn("No valid OTP found for user: {} with purpose: {}", user.getUsername(), purpose);
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                        .body(Map.of("code", "NO_OTP", "message", "No valid OTP found for purpose: " + purpose));
            }

            log.info("OTP retrieved for user: {} with purpose: {}", user.getUsername(), purpose);
            return ResponseEntity.ok(Map.of("otp", otp, "message", "OTP retrieved for Nexa user"));

        } catch (Exception e) {
            log.error("Failed to retrieve OTP with purpose: {} from IP: {}", purpose, httpRequest.getRemoteAddr(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("code", "ERROR", "message", "Failed to retrieve OTP: " + e.getMessage()));
        }
    }

    @PostMapping("/auth/logout")
    public ResponseEntity<?> logout(HttpServletRequest request) {
        try {
            String sessionId = null;
            HttpSession session = request.getSession(false);
            if (session != null) {
                sessionId = session.getId();
                session.invalidate();
            }
            SecurityContextHolder.clearContext();
            log.info("User logged out successfully from Nexa, session {} invalidated", sessionId);
            return ResponseEntity.ok(Map.of("message", "Logged out successfully from Nexa"));
        } catch (Exception e) {
            log.error("Logout error from IP {}: {}", request.getRemoteAddr(), e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(Map.of("code", "ERROR", "message", "Logout failed with Nexa"));
        }
    }
}